public enum TokenType {
    IDENTIFIANT, NOMBRE, CHAINE,
    MOT_CLE,         
    DEUX_POINTS, EGAL,
FIN_FICHIER ,PLUS, MOINS, MULTIPLIER, DIVISER,
SUPERIEUR, INFERIEUR, SUPERIEUR_EGAL, INFERIEUR_EGAL,
EGAL_EGAL, DIFFERENT,
PARENTHESE_OUVRANTE, PARENTHESE_FERMANT,
VIRGULE, POINT_VIRGULE                
}